import { Link } from "react-router-dom";

export default function AboutSection() {
  const stats = [
    {
      value: "10,000+",
      desc: "Sellers trained and onboarded across Indian marketplaces.",
    },
    {
      value: "₹15 Cr+",
      desc: "Cumulative gross merchandise value generated by our learners.",
    },
    {
      value: "3 Top Platforms",
      desc: "Deep specialization in Amazon, Meesho, and Flipkart algorithms.",
    },
    {
      value: "99.2% Success",
      desc: "Positive rating from sellers scaling their online stores.",
    },
  ];

  return (
    <section className="bg-white py-16 lg:py-24 border-t border-forest/10">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-16">
          {/* Left Content */}
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-leaf">
              About SkyBirds Academy
            </span>

            <h2 className="mt-3 text-3xl font-extrabold tracking-tight text-ink sm:text-4xl lg:text-[2.6rem] leading-tight">
              Empowering India's Next Generation of Marketplace Sellers
            </h2>

            <p className="mt-5 text-base leading-relaxed text-gray-600">
              SkyBirds is dedicated to bridging the gap between small manufacturers, D2C brands, and massive marketplace scale. We provide battle-tested playbooks, real-world case studies, and full onboarding services so you can sell profitably with zero guesswork.
            </p>

            {/* Stats Grid */}
            <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-2">
              {stats.map((stat) => (
                <div
                  key={stat.value}
                  className="rounded-xl border border-gray-200 bg-white p-3 lg:p-5 transition hover:border-leaf/50 hover:shadow-sm"
                >
                  <p className="text-xl font-bold text-forest">{stat.value}</p>
                  <p className="mt-1 text-xs leading-relaxed text-gray-500">
                    {stat.desc}
                  </p>
                </div>
              ))}
            </div>

            {/* CTA */}
            <div className="mt-8 flex gap-4">
              <Link
                to="/about"
                className="inline-flex items-center gap-2 rounded-full bg-leaf px-6 py-3 text-sm font-semibold text-white transition hover:bg-forest"
              >
                Learn More About Us →
              </Link>
            </div>
          </div>

          {/* Right Image / Showcase */}
          <div className="relative">
            <div className="overflow-hidden rounded-2xl border border-forest/10 shadow-lg">
              <img
                src="https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=900&q=80"
                alt="E-commerce seller packing orders"
                className="h-full w-full object-cover aspect-[4/3.5]"
              />
            </div>
            <div className="absolute -bottom-4 -left-4 -z-10 h-full w-full rounded-2xl bg-mint" />
          </div>
        </div>
      </div>
    </section>
  );
}
